package OntoExtract::Model::ontoextract;

use strict;

use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'OntoExtract::Schema',
    
    connect_info => {
       dsn => 'dbi:mysql:dbname=ontoextract',
        user => 'oe_admin',
        password => 'oe_admin_pass',
        mysql_enable_utf8 => 1,
    }
);

=head1 NAME

OntoExtract::Model::ontoextract - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<OntoExtract>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<OntoExtract::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.43

=head1 AUTHOR

Paixao

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
